name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - 'infrastructure-cd'
      - 'demo-releases/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: cd HeroesCup/HeroesCup.Web
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: /tmp/heroescup-web